### ISSUE TITLE
Remove dependency upon ltest

### ISSUE THREAD

**Issue by oubiwann** [lfex/clj#21]
Per @arpunk's ticket in the ltest project (see https://github.com/lfex/ltest/issues/34), I'm going to be removing the dep for ltest in clj. But we'll also need a long-term solution (as long as the clj project exists outside of LFE-proper). As such, this ticket has two parts:
1. [ ] Break the cyclic dependency experienced by ltest (and projects that wish to use ltest and clj as a dep)
2. [ ] Provide along-term solution for bringing ltest into the clj project (mostly for developers and contributors of the clj project)

There are several other approaches we can use. As we bump into a need for pulling down the dep, we can work around it. I'll leave ticket open until that second half is addressed.

**Comment by oubiwann** [comment]
Okay, it looks like I'd already done the first half of this last year:
- https://github.com/lfex/clj/commit/c0ae0a22cb4b9a382895320ddfc0edbd931c49ab#diff-31d7a50c99c265ca2793c20961b60979

**Comment by rvirding** [comment]
How do you mean "bring ltest into the clj project"? I do want to keep basic LFE very basic and make sure it does not depend on anything outside it (except erlang of course). So if the a clj library is included in lfe then it cannot not depend on anything outside lfe, the same as cl does today.

In the same way ltest should be careful on what it depends. What does it really need to depend on. So you avoid "wanting the banana and getting the whole gorilla" problem. It would also lessen the risk of version clashes. I am even doubtful I will include by beloved flavors in the core lfe.

**Comment by yurrriq** [comment]
We should put the `ltest` dependency in the `test` profile.

**Comment by oubiwann** [comment]
It turns out the dependencies for this were actually removed a while ago. I think the issue that the user was experiencing that caused this ticket to be opened was a combination of one or more older libraries.

Regardless: @yurrriq, I think that's a great idea. This removes a build/install cyclic dep but also lets the tests be run.

I'm going to close this issue and open one for doing that task.
